### ISSUE TITLE
etc/init.d/autoupdate问题

### ISSUE THREAD

**Issue by 281677160** [Hyy2001X/luci-app-autoupdate#3]
你好，Hyy2001X大神
使用新版的AutoUpdate.sh会遇到etc/openwrt_info文件的第二行会强制的变成仓库链接，这个是因为etc/init.d/autoupdate修改变更仓库地址的问题造成的，希望大神把文件修改一下，谢谢！
我只能用最笨的办法修改
current_github_url="$(cat /etc/openwrt_info | awk 'NR==改成链接对应的行数')"
sed -i "s?${current_github_url}?【增加Github=】${custom_github_url}?g" /etc/openwrt_info > /dev/null 2>&1

**Comment by Hyy2001X** [comment]
感谢反馈，我也遇到了这个问题但就是没找到问题所在，现在知道了，等我回去修复

**Comment by 281677160** [comment]
不客气，一直用你的定时更新，不过我是自己修改适配我自己仓库编译的，最早用的时候你都还没支持x86，后来我改了下自己用的，不过我感觉你最近修改的下载分加速跟不加速的不太好，我以前自己修改的是，检测当前网络，翻墙的就先不加速正常下载，正常下载不来就使用加速下载，反过来就是没翻墙的就先使用加速下载，下载不了就使用普通下载，都下不了就没办法了，你这样分开的手动选择感觉不好，因为自动更新的时候难道还要去选择吗，我把我代码贴一下，你看看，其实我不懂代码的，都是乱搞的，呵呵

if [[ "$(cat ${Download_Path}/Installed_PKG_List)" =~ curl ]];then
	export Google_Check=$(curl -I -s --connect-timeout 8 google.com -w %{http_code} | tail -n1)
	if [ ! "$Google_Check" == 301 ];then
		TIME r "梯子翻墙失败,优先使用[ FastGit镜像加速 ]下载,如果失败再转换成[ 普通方式 ]下载!"
		export PROXY_URL="https://download.fastgit.org"
		export DOWN_LOAD="[ FastGit镜像加速 ]"
	else
		TIME y "梯子翻墙成功,优先使用[ 普通方式 ]下载,如果失败再转换成[ FastGit镜像加速 ]下载!"
		export PROXY_URL="https://github.com"
		export DOWN_LOAD="[ 普通方式 ]"
	fi
fi
这个是判断网络那里的

[[ "${PROXY_URL}" == "https://github.com" ]] && {
	export Github_Release="${PROXY_URL}/${Apidz}/releases/download/update_Firmware"
	export PROXY_URLE="https://download.fastgit.org"
	export FastGit="[ FastGit镜像加速 ]"
	TIME g "正在使用${DOWN_LOAD}下载云端固件,请耐心等待..."
} || {
	export Github_Release="${PROXY_URL}/${Apidz}/releases/download/update_Firmware"
	export PROXY_URLE="https://github.com"
	export FastGit="[ 普通方式 ]"
	TIME g "正在使用${DOWN_LOAD}下载云端固件,请耐心等待..."
}
cd ${Download_Path}
wget -q --no-check-certificate -T 20 -t 3 "${Github_Release}/${Firmware}" -O ${Firmware}
if [[ $? -ne 0 ]];then
	TIME r "${DOWN_LOAD}下载云端固件失败,转换成${FastGit}下载,请耐心等待... !"
	export Github_Release="${PROXY_URLE}/${Apidz}/releases/download/update_Firmware"
	wget -q --no-check-certificate -T 20 -t 3 "${Github_Release}/${Firmware}" -O ${Firmware}
	if [[ $? -ne 0 ]];then
		TIME r "下载云端固件失败,请尝试手动安装!"
		exit 1
	else
		TIME y "使用${FastGit}下载云端固件成功!"
	fi
else
	TIME y "使用${DOWN_LOAD}下载云端固件成功!"
fi
这个是下载的时候的，MD5也一样，不过下载固件速度快，下载MD5会卡半天，有时候固件能下好，MD5那里卡的下不来，不知道原因，或者跟文件格式有关？

**Comment by Hyy2001X** [comment]
会自动判断网络类型然后自动选择是否代理加速，-p的作用是强制代理加速

**Comment by 281677160** [comment]
我的意思是判断走不走代理加速还不够的，代理加速经常下不来，不走代理也有时候下不来，干脆就让它两个都下，代理加速下不了转换成不代理的继续下，如果不走代理的下不来就代理加速继续下，呃，说的有点乱，不知道你能理解不

**Comment by 281677160** [comment]
判断当前网络，比如当前网络为翻墙网络
优先使用普通下载，判断普通下载成功不成功，不成功转换成代理加速下载，还是下载不了就没办法了

判断当前网络，比如当前网络为不是翻墙网络
优先使用代理加速下载，判断代理加速下载成功不成功，不成功转换成普通不走代理的继续下载，还是下载不了就没办法了

**Comment by 281677160** [comment]
![QQ截图20210517125525](https://user-images.githubusercontent.com/66651997/118434257-53028a80-b70f-11eb-9a0a-6781904d5be5.png)

**Comment by 281677160** [comment]
![QQ截图20210517125618](https://user-images.githubusercontent.com/66651997/118434275-5dbd1f80-b70f-11eb-806e-3d1186580864.png)

**Comment by 281677160** [comment]
把修改好的AutoUpdate.sh文件编译了一个新固件，然后发现了命令修改链接的话，单纯修改openwrt_info文件是不行的，还得要修改/etc/config/autoupdate 这个文件里面的链接，要不然重启系统后就会变成在这个文件里面的链接了，等于没改

**Comment by Hyy2001X** [comment]
已优化相关策略

**Comment by Hyy2001X** [comment]
> 把修改好的AutoUpdate.sh文件编译了一个新固件，然后发现了命令修改链接的话，单纯修改openwrt_info文件是不行的，还得要修改/etc/config/autoupdate 这个文件里面的链接，要不然重启系统后就会变成在这个文件里面的链接了，等于没改

已修复

**Comment by 281677160** [comment]
感谢修复！
刚才又发现了一个小问题，不过不影响吧，就是那个测试模式的，运行到最后加2个代码比较好
增加  opkg remove gzip  这个是御载gzip的，安装了这个ipk后不御载的话，你用openwrt后台的更换固件都更换不了，x86设备openwrt后台用的是.img.gz格式，拉进去就给解压了，更新不了。其实这个不安装，你的文件都可以更新.img.gz固件的，.img没测试

增加  rm -rf /tmp/Downloads 这个是删除下载的

**Comment by Hyy2001X** [comment]
> 感谢修复！
> 刚才又发现了一个小问题，不过不影响吧，就是那个测试模式的，运行到最后加2个代码比较好
> 增加 opkg remove gzip 这个是御载gzip的，安装了这个ipk后不御载的话，你用openwrt后台的更换固件都更换不了，x86设备openwrt后台用的是.img.gz格式，拉进去就给解压了，更新不了。其实这个不安装，你的文件都可以更新.img.gz固件的，.img没测试
> 
> 增加 rm -rf /tmp/Downloads 这个是删除下载的

-t测试模式是我自己用来测试脚本功能用的~不影响
