### ISSUE TITLE
大神您好！

### ISSUE THREAD

**Issue by 281677160** [Hyy2001X/luci-app-autoupdate#4]
我用的是X86设备，这两天测试了一下转换引导模式的，有安装不了固件的时候，就是更改了引导模式后，再次更新固件会卡了，不会安装固件了，还有就是如果别人用爱快的虚拟机安装固件的话，不管你是Legacy还是uefi的都会给你默认安装成Legacy，如果你去更改引导的话，100%安装不了固件
我能想到的解决方法也挺简单的，更改引导的时候写一个文件到到etc里面，比如echo "${Input_Other}" > /etc/Input_Other
到了最后使用命令的时候就写一个判断
检测有没有Input_Other这个文件，有就用 sysupgrade ${Upgrade_Options} -F ${Firmware} 这个命令，多了个-F强制安装，不止更换引导，更换其他源码的固件都可以安装，会不会有什么不良效果，我也不知道了，我测试了5~6次，感觉用着也没什么问题

**Comment by Hyy2001X** [comment]
感谢反馈!已优化脚本,使用 autoupdate -f 参数强制更新即可

**Comment by 281677160** [comment]
不方便啊，比如我修改了引导，我又没用更新命令，下次我都忘记了这回事了，等我再用命令的时候，或者定时更新，到了时间自动更新，它就不会考虑你更改过引导，结果就有概率给卡了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年6月12日(周六) 下午5:32
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Hyy2001X/luci-app-autoupdate] 大神您好！ (#4)




 
感谢反馈!已优化脚本,使用 autoupdate -f 参数强制更新即可

**Comment by Hyy2001X** [comment]
> 不方便啊，比如我修改了引导，我又没用更新命令，下次我都忘记了这回事了，等我再用命令的时候，或者定时更新，到了时间自动更新，它就不会考虑你更改过引导，结果就有概率给卡了
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2021年6月12日(周六) 下午5:32 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [Hyy2001X/luci-app-autoupdate] 大神您好！ (#4) 感谢反馈!已优化脚本,使用 autoupdate -f 参数强制更新即可 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

sysupgrade -F 强制刷写固件有风险,不适合定时更新

**Comment by 281677160** [comment]
我明白你意思，我的意思是更改引导模式后，第一次更新安装固件的时候自动判断使用强制更新比较方便而已，第一次过后就不会强制了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年6月12日(周六) 晚上6:03
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Hyy2001X/luci-app-autoupdate] 大神您好！ (#4)




  
不方便啊，比如我修改了引导，我又没用更新命令，下次我都忘记了这回事了，等我再用命令的时候，或者定时更新，到了时间自动更新，它就不会考虑你更改过引导，结果就有概率给卡了
 …
 ---原始邮件--- 发件人: @.&gt; 发送时间: 2021年6月12日(周六) 下午5:32 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [Hyy2001X/luci-app-autoupdate] 大神您好！ (#4) 感谢反馈!已优化脚本,使用 autoupdate -f 参数强制更新即可 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
sysupgrade -F 强制刷写固件有风险,不适合定时更新

**Comment by Hyy2001X** [comment]
> 我明白你意思，我的意思是更改引导模式后，第一次更新安装固件的时候自动判断使用强制更新比较方便而已，第一次过后就不会强制了
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2021年6月12日(周六) 晚上6:03 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [Hyy2001X/luci-app-autoupdate] 大神您好！ (#4) 不方便啊，比如我修改了引导，我又没用更新命令，下次我都忘记了这回事了，等我再用命令的时候，或者定时更新，到了时间自动更新，它就不会考虑你更改过引导，结果就有概率给卡了 … ---原始邮件--- 发件人: @.&gt; 发送时间: 2021年6月12日(周六) 下午5:32 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [Hyy2001X/luci-app-autoupdate] 大神您好！ (#4) 感谢反馈!已优化脚本,使用 autoupdate -f 参数强制更新即可 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. sysupgrade -F 强制刷写固件有风险,不适合定时更新 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

已按照你的建议修改 -B 参数

**Comment by 281677160** [comment]
https://github.com/281677160/common/blob/main/AutoUpdate.sh
我胡乱的搞了个更改其他作者固件的，都乱搞的，写的乱78糟，哈哈，不过方便我自己玩，我一次编译3个作者的源码，以前换其他作者的固件只能下载再手动更换，现在倒是方便多了
还有就是我把MD5文件跟固件打包成tar.gz的格式，一次下载两，比较方便，就是不知道k2p那些路由器的tmp空间有多大的，要超过32M才够解压，tmp空间是运行内存的一半，我想大多数路由器都有64M内存吧
![QQ截图20210612212323](https://user-images.githubusercontent.com/66651997/121777519-271add80-cbc5-11eb-9482-01574647d0e3.png)

**Comment by 281677160** [comment]
大神，把那些修改都弄成这样的修改法，会不会更直观啊？
我可说明了，我不懂代码的，都是靠抄滴，呵呵
![QQ截图20210613124557](https://user-images.githubusercontent.com/66651997/121796717-cf748480-cc4d-11eb-9df9-77d893906ca1.png)
![QQ截图20210613134338](https://user-images.githubusercontent.com/66651997/121796723-d3080b80-cc4d-11eb-98de-d6e85fc20608.png)
